import{a as L,S as w,i as l}from"./assets/vendor-BxTtOiNT.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))u(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const c of o.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&u(c)}).observe(document,{childList:!0,subtree:!0});function r(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function u(e){if(e.ep)return;e.ep=!0;const o=r(e);fetch(e.href,o)}})();const v="50507982-c6a73d82cfbe0bce0234dfd9b",S="https://pixabay.com/api/";async function p(s){console.log("getImagesByQuery");try{return(await L.get(S,{params:{key:v,q:s,image_type:"photo",orientation:"horizontal",safesearch:!0}})).data}catch(t){throw t}}let E=new w(".gallery a",{captionsData:"alt",captionDelay:250});const m=document.querySelector(".gallery"),y=document.querySelector(".loader");function h(s){const t=s.map(r=>`<div class="photo-card">
        <a href="${r.largeImageURL}">
          <img src="${r.webformatURL}" alt="${r.tags}" loading="lazy" />
        </a>
        <div class="info">
          <p class="info-item"><b>Likes</b><span>${r.likes}</span></p>
          <p class="info-item"><b>Views</b><span>${r.views}</span></p>
          <p class="info-item"><b>Comments</b><span>${r.comments}</span></p>
          <p class="info-item"><b>Downloads</b><span>${r.downloads}</span></p>
        </div>
      </div>`).join("");m.insertAdjacentHTML("beforeend",t),E.refresh()}function I(){m.innerHTML=""}function g(){y.classList.remove("hidden")}function b(){y.classList.add("hidden")}const $=document.querySelector("#search-form"),f=document.querySelector(".load-more");let n="",a=1,d=0;i();$.addEventListener("submit",async s=>{if(s.preventDefault(),n=s.target.elements.searchQuery.value.trim(),!!n){I(),i(),a=1,g();try{const{hits:t,totalHits:r}=await p(n,a);if(d=r,t.length===0){l.info({message:"No images found. Try another keyword!"});return}h(t),d>t.length&&q()}catch{l.error({message:"Error fetching images"})}finally{b()}}});f.addEventListener("click",async()=>{a++,g(),i();try{const{hits:s}=await p(n,a);h(s),a*40>=d&&i()}catch{l.error({message:"Error loading more images"})}finally{b()}});function q(){f.style.display="block"}function i(){f.style.display="none"}
//# sourceMappingURL=index.js.map
